/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorUsuario;
import javax.swing.table.DefaultTableModel;
import modeloAnimales.Animal;
import modeloAnimales.HistoriaClinica;
import modeloPersonas.CriadorCerdo;
import modeloPersonas.EncargadoCaballo;
import modeloPersonas.EncargadoGanado;
import modeloPersonas.Usuario;

/**
 *
 * @author SANTIAGO
 */
public class VistaHistorialClinico extends javax.swing.JFrame {

    /**
     * Creates new form VistaHistorialClinico
     */
    VistaLogIn vistaLogIn;
    DefaultTableModel modeloHistoriaClinica;
    Animal animal;
    ControladorUsuario controladorUsuario;
    int fila;
    int columna;

    public VistaHistorialClinico(VistaLogIn vistaLogIn, Animal animal, int fila, int columna) {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaLogIn = vistaLogIn;
        this.animal = animal;
        this.fila = fila;
        this.columna = columna;
        controladorUsuario = vistaLogIn.getControladorUsuario();
        declararColumnasTabla();
        cargarTabla();
        llenarJlabels();
        reducirEspacioColumnaFecha();
    }

    private void llenarJlabels() {
        textoCodigo.setText(animal.getCodigoString());
        textoGenero.setText(animal.getGenero());
        textoNombre.setText(animal.getNombre());
    }

    private void reducirEspacioColumnaFecha() {
        tblHistorial.getColumnModel().getColumn(1).setMaxWidth(100);
        tblHistorial.getColumnModel().getColumn(1).setMinWidth(100);
        tblHistorial.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        tblHistorial.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        tblHistorial.getTableHeader().getColumnModel().getColumn(1).setMinWidth(100);
    }

    private void cargarTabla() {
        for (int i = 0; i < animal.obtenerTamañoListaHistorial(); i++) {
            HistoriaClinica historiaClinica = animal.recorrerListaHistoriaClinica(i);
            String datos[] = new String[2];
            datos[0] = historiaClinica.getDiagnostico();
            datos[1] = historiaClinica.getFecha();
            modeloHistoriaClinica.addRow(datos);
        }
    }

    private void declararColumnasTabla() {
        modeloHistoriaClinica = new DefaultTableModel();
        modeloHistoriaClinica.addColumn("Diagnostico");
        modeloHistoriaClinica.addColumn("Fecha");
        this.tblHistorial.setModel(modeloHistoriaClinica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoGenero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial clínico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Información del animal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 40, -1, -1));

        jLabel2.setText("Código:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 74, -1, -1));

        textoCodigo.setText("jLabel3");
        jPanel1.add(textoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 74, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 74, -1, -1));

        textoNombre.setText("jLabel4");
        jPanel1.add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 74, -1, -1));

        jLabel4.setText("Genero:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 74, -1, -1));

        textoGenero.setText("jLabel5");
        jPanel1.add(textoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 74, -1, -1));

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHistorial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 126, 670, 334));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 700, 480));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 506, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VistaListaAnimales vista = new VistaListaAnimales(vistaLogIn, fila, columna);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoGenero;
    private javax.swing.JLabel textoNombre;
    // End of variables declaration//GEN-END:variables
}
