/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author SANTIAGO
 */
public class VistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministrador
     */
    VistaLogIn vistaLogIn;
    public static String rolEscogido = " ";

    public VistaAdministrador(VistaLogIn vistaLogIn) {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaLogIn = vistaLogIn;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGestionUsuarios = new javax.swing.JButton();
        btnRegistrarUsuarios = new javax.swing.JButton();
        btnAccionCriadorCerdo = new javax.swing.JButton();
        btnAccionEncargadoCaballos = new javax.swing.JButton();
        btnAccionEncargadoGanado = new javax.swing.JButton();
        btnVeterinario = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionUsuarios.setText("Gestionar usuarios");
        btnGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 89, -1, -1));

        btnRegistrarUsuarios.setText("Registrar usuario");
        btnRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 41, -1, -1));

        btnAccionCriadorCerdo.setText("Acción criador cerdo");
        btnAccionCriadorCerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionCriadorCerdoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccionCriadorCerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 139, -1, -1));

        btnAccionEncargadoCaballos.setText("Acción encargado caballos");
        btnAccionEncargadoCaballos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionEncargadoCaballosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccionEncargadoCaballos, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 241, -1, -1));

        btnAccionEncargadoGanado.setText("Acción encargado ganado");
        btnAccionEncargadoGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionEncargadoGanadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccionEncargadoGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 191, -1, -1));

        btnVeterinario.setText("Veterinario");
        btnVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeterinarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 284, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 360, 340));

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/Admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 550, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuariosActionPerformed
        // TODO add your handling code here:
        VistaGestionInfoUsuario vista = new VistaGestionInfoUsuario(vistaLogIn);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionUsuariosActionPerformed

    private void btnRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuariosActionPerformed
        // TODO add your handling code here:
        VistaRegistro vista = new VistaRegistro(vistaLogIn);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarUsuariosActionPerformed

    private void btnAccionCriadorCerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionCriadorCerdoActionPerformed
        // TODO add your handling code here:
        VistaCriadorDeCerdo vista = new VistaCriadorDeCerdo(vistaLogIn);
        vista.setVisible(true);
        rolEscogido = "Cerdo";
        this.dispose();
    }//GEN-LAST:event_btnAccionCriadorCerdoActionPerformed

    private void btnAccionEncargadoCaballosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionEncargadoCaballosActionPerformed
        // TODO add your handling code here:
        VistaEncargadoDelCaballo vista = new VistaEncargadoDelCaballo(vistaLogIn);
        vista.setVisible(true);
        rolEscogido = "Caballo";
        this.dispose();
    }//GEN-LAST:event_btnAccionEncargadoCaballosActionPerformed

    private void btnAccionEncargadoGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionEncargadoGanadoActionPerformed
        // TODO add your handling code here:
        VistaEncargadoDelGanado vista = new VistaEncargadoDelGanado(vistaLogIn);
        vista.setVisible(true);
        rolEscogido = "Ganado";
        this.dispose();
    }//GEN-LAST:event_btnAccionEncargadoGanadoActionPerformed

    private void btnVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeterinarioActionPerformed
        // TODO add your handling code here:
        VistaVeterinario vista = new VistaVeterinario(vistaLogIn);
        vista.setVisible(true);
        rolEscogido = "Veterinario";
        this.dispose();
    }//GEN-LAST:event_btnVeterinarioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccionCriadorCerdo;
    private javax.swing.JButton btnAccionEncargadoCaballos;
    private javax.swing.JButton btnAccionEncargadoGanado;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionUsuarios;
    private javax.swing.JButton btnRegistrarUsuarios;
    private javax.swing.JButton btnVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
