/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import excepciones.CompletarCampoVacioException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modeloAnimales.AccionRealizadaAnimal;
import modeloAnimales.Caballo;
import modeloAnimales.CuidadoCaballo;
import modeloPersonas.EncargadoCaballo;
import modeloPersonas.Usuario;

/**
 *
 * @author SANTIAGO
 */
public class VistaCuidadosCaballo extends javax.swing.JFrame {

    /**
     * Creates new form VistaCuidadosCaballo
     */
    VistaLogIn vistaLogIn;
    DefaultTableModel modeloCuidados;
    int fila;
    int columna;
    Caballo animal;

    public VistaCuidadosCaballo(VistaLogIn vistaLogIn, Caballo animal, int fila, int columna) {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaLogIn = vistaLogIn;
        this.animal = animal;
        this.fila = fila;
        this.columna = columna;
        declararColumnasTabla();
        reducirEspacioColumnaFecha();
        cargarTabla();
        validarTextos();
    }

    private void validarTextos() {
        textoCodigo.setText(animal.getCodigoString());
        textoGenero.setText(animal.getGenero());
        textoNombre.setText(animal.getNombre());
    }

    private void declararColumnasTabla() {
        modeloCuidados = new DefaultTableModel();
        modeloCuidados.addColumn("Cuidado");
        modeloCuidados.addColumn("Año");
        this.tblCuidadosCaballo.setModel(modeloCuidados);
    }

    private void reducirEspacioColumnaFecha() {
        tblCuidadosCaballo.getColumnModel().getColumn(1).setMaxWidth(100);
        tblCuidadosCaballo.getColumnModel().getColumn(1).setMinWidth(100);
        tblCuidadosCaballo.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        tblCuidadosCaballo.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        tblCuidadosCaballo.getTableHeader().getColumnModel().getColumn(1).setMinWidth(100);
    }

    private void cargarTabla() {
        for (int i = 0; i < animal.obtenerTamañoListaCuidados(); i++) {
            CuidadoCaballo cuidado = animal.recorrerListaCuidados(i);
            String[] datos = new String[2];
            datos[0] = cuidado.getCuidado();
            datos[1] = cuidado.getFecha();
            modeloCuidados.addRow(datos);
        }
    }

    private void agregarCuidadoTabla(CuidadoCaballo cuidado) {
        String[] datos = new String[2];
        datos[0] = cuidado.getCuidado();
        datos[1] = cuidado.getFecha();
        modeloCuidados.addRow(datos);
    }

    public static String obtenerFechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        return formato.format(fecha);
    }

    private void eliminarObjetosTabla() {
        modeloCuidados.setRowCount(0);
    }

    private void limpiarCampos() {
        txtCuidado.setText(null);
    }

    private void añadirCuidadoAlEpmpleado() {
        Usuario usuario = vistaLogIn.getControladorUsuario().getUsuarioLogueado();
        if (usuario instanceof EncargadoCaballo) {
            ((EncargadoCaballo) usuario).añadirCuidado();
            vistaLogIn.getControladorUsuario().escribirUsuarios();
        }
    }

    private void eliminarCuidadoAlEmpleado() {
        Usuario usuario = vistaLogIn.getControladorUsuario().getUsuarioLogueado();
        if (usuario instanceof EncargadoCaballo) {
            ((EncargadoCaballo) usuario).restarCuidadoo();
            vistaLogIn.getControladorUsuario().escribirUsuarios();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCuidado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarCuidado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuidadosCaballo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoGenero = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuidados del caballo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cuidado\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        txtCuidado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCuidado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCuidadoMouseClicked(evt);
            }
        });
        txtCuidado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuidadoKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuidado realizado");

        btnRegistrarCuidado.setText("Registrar cuidado");
        btnRegistrarCuidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCuidadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtCuidado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnRegistrarCuidado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuidado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRegistrarCuidado)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        tblCuidadosCaballo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCuidadosCaballo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 110, 299, 226));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Información del caballo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 31, -1, -1));

        textoCodigo.setForeground(new java.awt.Color(255, 255, 255));
        textoCodigo.setText("code");
        jPanel1.add(textoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 65, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 65, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 65, -1, -1));

        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setText("jLabel6");
        jPanel1.add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 65, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Género: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 65, -1, -1));

        textoGenero.setForeground(new java.awt.Color(255, 255, 255));
        textoGenero.setText("jLabel7");
        jPanel1.add(textoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 65, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 610, 350));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        btnAdelante.setText("Adelante");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/cuidados-del-caballo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 630, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuidadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCuidadoMouseClicked
        // TODO add your handling code here:
        txtCuidado.setText(null);
    }//GEN-LAST:event_txtCuidadoMouseClicked

    private void btnRegistrarCuidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCuidadoActionPerformed
        // TODO add your handling code here:
        try {
            if (txtCuidado.getText().isEmpty()) {
                throw new CompletarCampoVacioException();
            }
            String cuidado = txtCuidado.getText();
            String fecha = obtenerFechaActual();
            CuidadoCaballo cuidadoCaballo = new CuidadoCaballo(cuidado, fecha);
            animal.agregarCuidadoAlCaballo(cuidadoCaballo);
            agregarCuidadoTabla(cuidadoCaballo);
            AccionRealizadaAnimal accion = new AccionRealizadaAnimal(animal, AccionRealizadaAnimal.REGISTRAR);
            vistaLogIn.getControladorPila().pushAccionPilaUnoAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaCuidadosUno(cuidadoCaballo);
            JOptionPane.showMessageDialog(null, "Se registró el cuidado del caballo.");
            limpiarCampos();
            añadirCuidadoAlEpmpleado();
            vistaLogIn.getControladorPesebrera().escribirPesebreras();
        } catch (CompletarCampoVacioException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarCuidadoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VistaListaAnimales vista = new VistaListaAnimales(vistaLogIn, fila, columna);
        vista.setVisible(true);
        this.dispose();
        vistaLogIn.getControladorPila().limpiarPilas();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        if (vistaLogIn.getControladorPila().pilaUnoAnimalesIsEmpty() == false) {
            AccionRealizadaAnimal accion = vistaLogIn.getControladorPila().popAccionPilaUnoAnimales();
            CuidadoCaballo cuidado = null;
            if (accion.getAccion().equals(AccionRealizadaAnimal.REGISTRAR)) {
                Caballo caballo = (Caballo) accion.getAnimal();
                cuidado = vistaLogIn.getControladorPila().popPilaCuidadosUno();
                caballo.eliminarCuidado(cuidado);
                eliminarCuidadoAlEmpleado();
                vistaLogIn.getControladorPesebrera().escribirPesebreras();
                accion.setAccion(AccionRealizadaAnimal.ELIMINAR);
                eliminarObjetosTabla();
                cargarTabla();
            }
            vistaLogIn.getControladorPila().pushAccionPilaDosAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaCuidadosDos(cuidado);
        } else {
            JOptionPane.showMessageDialog(null, "No se puede retroceder mas.");
        }

    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        if (vistaLogIn.getControladorPila().pilaDosAnimalesIsEmpty() == false) {
            AccionRealizadaAnimal accion = vistaLogIn.getControladorPila().popAccionPilaDosAnimales();
            CuidadoCaballo cuidado = null;
            if (accion.getAccion().equals(AccionRealizadaAnimal.ELIMINAR)) {
                Caballo caballo = (Caballo) accion.getAnimal();
                cuidado = vistaLogIn.getControladorPila().popPilaCuidadosDos();
                caballo.agregarCuidadoAlCaballo(cuidado);
                vistaLogIn.getControladorPesebrera().escribirPesebreras();
                añadirCuidadoAlEpmpleado();
                accion.setAccion(AccionRealizadaAnimal.REGISTRAR);
                eliminarObjetosTabla();
                cargarTabla();
            }
            vistaLogIn.getControladorPila().pushAccionPilaUnoAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaCuidadosUno(cuidado);
        } else {
            JOptionPane.showMessageDialog(null, "No se puede adelantar mas.");
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void txtCuidadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuidadoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuidadoKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrarCuidado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCuidadosCaballo;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoGenero;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JTextField txtCuidado;
    // End of variables declaration//GEN-END:variables

}
