/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorColaVeterinario;
import controladores.ControladorUsuario;
import excepciones.ColaVaciaException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modeloAnimales.AccionRealizadaAnimal;
import modeloAnimales.Animal;
import modeloAnimales.Caballo;
import modeloAnimales.Cerdo;
import modeloAnimales.HistoriaClinica;
import modeloPersonas.Administrador;
import modeloPersonas.Usuario;
import modeloPersonas.Veterinario;
import util.Cola;

/**
 *
 * @author SANTIAGO
 */
public class VistaVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form VistaVeterinario
     */
    VistaLogIn vistaLogIn;
    ControladorUsuario controladorUsuario;
    ControladorColaVeterinario colaAnimales;

    public VistaVeterinario(VistaLogIn vistaLogIn) {
        initComponents();
        setLocationRelativeTo(this);
        controladorUsuario = vistaLogIn.getControladorUsuario();
        colaAnimales = vistaLogIn.getControladorColaVeterinario();
        this.vistaLogIn = vistaLogIn;
        btnVolver.setVisible(false);
        validarUsuarioLogeado();
        bloquearCampos();
        llenarCampos();
    }

    public static String obtenerFechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        return formato.format(fecha);
    }

    private void limpiarCampos() {
        txtCodigoAnimal.setText(null);
        txtGeneroAnimal.setText(null);
        txtProblema.setText(null);
        txtTipoAnimal.setText(null);
        txtNombre.setText(null);
    }

    private void bloquearCampos() {
        txtCodigoAnimal.setEditable(false);
        txtGeneroAnimal.setEditable(false);
        txtProblema.setEditable(false);
        txtTipoAnimal.setEditable(false);
        txtNombre.setEditable(false);
    }

    private void llenarCampos() {
        try {
            Animal animal = colaAnimales.frente();
            txtCodigoAnimal.setText(animal.getCodigoString());
            txtGeneroAnimal.setText(animal.getGenero());
            txtProblema.setText(animal.getProblemaRemisionVeterinario());
            txtNombre.setText(animal.getNombre());
            if (animal instanceof Cerdo) {
                txtTipoAnimal.setText("Cerdo");
            } else if (animal instanceof Caballo) {
                txtTipoAnimal.setText("Caballo");
            } else {
                txtTipoAnimal.setText("Vacuno");
            }
        } catch (ColaVaciaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void validarUsuarioLogeado() {
        Usuario usuarioLogeado = controladorUsuario.getUsuarioLogueado();
        if (usuarioLogeado instanceof Administrador) {
            btnVolver.setVisible(true);
            btnAtenderAnimal.setEnabled(false);
        }
    }

    private void añadirAnimalAtendido() {
        Usuario usuario = vistaLogIn.getControladorUsuario().getUsuarioLogueado();
        if (usuario instanceof Veterinario) {
            ((Veterinario) usuario).añadirAnimalAtendido();
            controladorUsuario.escribirUsuarios();
        }
    }
    
    private void eliminarAnimalAtendido() {
        Usuario usuario = vistaLogIn.getControladorUsuario().getUsuarioLogueado();
        if (usuario instanceof Veterinario) {
            ((Veterinario) usuario).restarAnimalAtendido();
            controladorUsuario.escribirUsuarios();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAtenderAnimal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTipoAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoAnimal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGeneroAnimal = new javax.swing.JTextField();
        txtProblema = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veterinario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Información siguiente animal");

        btnAtenderAnimal.setText("Atender Animal");
        btnAtenderAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderAnimalActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo");

        txtTipoAnimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código");

        txtCodigoAnimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Género");

        txtGeneroAnimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Problema descrito");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtGeneroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnAtenderAnimal)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtenderAnimal)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, 300));

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        btnAdelante.setText("Adelante");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/Vete.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VistaAdministrador vista = new VistaAdministrador(vistaLogIn);
        vista.setVisible(true);
        this.dispose();
        vistaLogIn.getControladorPila().limpiarPilas();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAtenderAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderAnimalActionPerformed
        // TODO add your handling code here:
        try {
            colaAnimales.isEmpty();
            Animal animal = colaAnimales.desencolar();
            VistaObservacionVeterinario vista = new VistaObservacionVeterinario(vistaLogIn, animal);
            vista.setVisible(true);
            this.dispose();
            limpiarCampos();
            
        } catch (ColaVaciaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnAtenderAnimalActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        if (vistaLogIn.getControladorPila().pilaDosAnimalesIsEmpty() == false) {
            AccionRealizadaAnimal accion = vistaLogIn.getControladorPila().popAccionPilaDosAnimales();
            if (accion.getAccion().equals(AccionRealizadaAnimal.ELIMINAR)) {
                System.out.println("Se elimina");
                Animal animal = colaAnimales.desencolar();
                HistoriaClinica historiaClinica = vistaLogIn.getControladorPila().popPilaHistoriaClinicaDos();
                animal.añadirAlHistorialClinico(historiaClinica);
                añadirAnimalAtendido();
                limpiarCampos();
                llenarCampos();
                vistaLogIn.getControladorPila().pushPilaHistoriaClinicaUno(historiaClinica);
                accion.setAccion(AccionRealizadaAnimal.REGISTRAR);
            }
            vistaLogIn.getControladorPila().pushAccionPilaUnoAnimales(accion);
        } else {
            JOptionPane.showMessageDialog(null, "No se puede adelantar mas");
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
////        System.out.println("Lo que llego de pila dos: " + vistaLogIn.getControladorPila().popPilaHistoriaClinicaUno());
        if (vistaLogIn.getControladorPila().pilaUnoAnimalesIsEmpty() == false) {
            AccionRealizadaAnimal accion = vistaLogIn.getControladorPila().popAccionPilaUnoAnimales();
            HistoriaClinica historiaClinica = null;
            if (accion.getAccion().equals(AccionRealizadaAnimal.REGISTRAR)) {
                Animal animal = accion.getAnimal();
                historiaClinica = vistaLogIn.getControladorPila().popPilaHistoriaClinicaUno();
                animal.eliminarHistorialClinico(historiaClinica);
                colaAnimales.ponerFrente(animal);
                eliminarAnimalAtendido();
                llenarCampos();
                accion.setAccion(AccionRealizadaAnimal.ELIMINAR);
            }
            vistaLogIn.getControladorPila().pushAccionPilaDosAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaHistoriaClinicaDos(historiaClinica);
        } else {
            JOptionPane.showMessageDialog(null, "No se puede retroceder mas.");
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtenderAnimal;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigoAnimal;
    private javax.swing.JTextField txtGeneroAnimal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProblema;
    private javax.swing.JTextField txtTipoAnimal;
    // End of variables declaration//GEN-END:variables
}
