/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import excepciones.CompletarCampoVacioException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modeloAnimales.AccionRealizadaAnimal;
import modeloAnimales.Animal;
import modeloAnimales.HistoriaClinica;
import modeloPersonas.Usuario;
import modeloPersonas.Veterinario;

/**
 *
 * @author SANTIAGO
 */
public class VistaObservacionVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form VistaObservacionVeterinario
     */
    Animal animal;
    VistaLogIn vistaLogIn;

    public VistaObservacionVeterinario(VistaLogIn vistaLogIn, Animal animal) {
        initComponents();
        setLocationRelativeTo(this);
        this.animal = animal;
        this.vistaLogIn = vistaLogIn;
    }

    public static String obtenerFechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        return formato.format(fecha);
    }

    private void añadirAnimalAtendido() {
        Usuario usuario = vistaLogIn.getControladorUsuario().getUsuarioLogueado();
        if (usuario instanceof Veterinario) {
            ((Veterinario) usuario).añadirAnimalAtendido();
            vistaLogIn.getControladorUsuario().escribirUsuarios();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        txtObservacion.setText("Escriba aqui, la observación del animal...");
        txtObservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtObservacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacion);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtObservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObservacionMouseClicked
        // TODO add your handling code here:
        txtObservacion.setText(null);
    }//GEN-LAST:event_txtObservacionMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtObservacion.getText().isEmpty() || txtObservacion.getText().equals("Escriba aqui, la observación del animal...")) {
                throw new CompletarCampoVacioException();
            }
            String diagnostico = txtObservacion.getText();
            HistoriaClinica historiaClinica = new HistoriaClinica(obtenerFechaActual(), diagnostico);
            animal.añadirAlHistorialClinico(historiaClinica);
            añadirAnimalAtendido();
            AccionRealizadaAnimal accion = new AccionRealizadaAnimal(animal, AccionRealizadaAnimal.REGISTRAR);
            vistaLogIn.getControladorPila().pushAccionPilaUnoAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaHistoriaClinicaUno(historiaClinica);
            JOptionPane.showMessageDialog(null, "Se ha atendido el animal.");
            VistaVeterinario vista = new VistaVeterinario(vistaLogIn);
            vista.setVisible(true);
            this.dispose();
        } catch (CompletarCampoVacioException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtObservacion;
    // End of variables declaration//GEN-END:variables
}
