/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import excepciones.CompletarCampoVacioException;
import excepciones.ObjetoTablaNoSeleccionadoException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modeloAnimales.AccionRealizadaAnimal;
import modeloAnimales.Animal;
import modeloAnimales.Caballo;
import modeloAnimales.PremioCaballo;

/**
 *
 * @author SANTIAGO
 */
public class VistaRegistroPremiosCaballo extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroPremiosCaballo
     */
    VistaLogIn vistaLogIn;
    DefaultTableModel modeloPremios;
    int fila;
    int columna;
    Caballo animal;

    public VistaRegistroPremiosCaballo(VistaLogIn vistaLogIn, Caballo animal, int fila, int columna) {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaLogIn = vistaLogIn;
        this.animal = animal;
        this.fila = fila;
        this.columna = columna;
        declararColumnasTabla();
        reducirEspacioColumnaFecha();
        cargarTabla();
        validarTextos();
    }

    private void validarTextos() {
        textoCodigo.setText(animal.getCodigoString());
        textoGenero.setText(animal.getGenero());
        textoNombre.setText(animal.getNombre());
    }

    private void limpiarCampos() {
        txtPremio.setText(null);
        txtAño.setText(null);
    }

    private void declararColumnasTabla() {
        modeloPremios = new DefaultTableModel();
        modeloPremios.addColumn("Premio");
        modeloPremios.addColumn("Año");
        this.tblPremiosCaballo.setModel(modeloPremios);
    }

    private void agregarPremioTabla(PremioCaballo premio) {
        String[] datos = new String[2];
        datos[0] = premio.getPremio();
        datos[1] = premio.getFecha();
        modeloPremios.addRow(datos);
    }

    private void cargarTabla() {
        for (int i = 0; i < animal.obtenerTamañoListaPremios(); i++) {
            PremioCaballo premio = animal.recorrerListaPremios(i);
            String[] datos = new String[2];
            datos[0] = premio.getPremio();
            datos[1] = premio.getFecha();
            modeloPremios.addRow(datos);
        }
    }

    private void reducirEspacioColumnaFecha() {
        tblPremiosCaballo.getColumnModel().getColumn(1).setMaxWidth(100);
        tblPremiosCaballo.getColumnModel().getColumn(1).setMinWidth(100);
        tblPremiosCaballo.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        tblPremiosCaballo.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        tblPremiosCaballo.getTableHeader().getColumnModel().getColumn(1).setMinWidth(100);
    }

    private void eliminarObjetosTabla() {
        modeloPremios.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtPremio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPremiosCaballo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoGenero = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion premios del caballo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos premio\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtPremio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPremio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPremioMouseClicked(evt);
            }
        });
        txtPremio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPremioKeyTyped(evt);
            }
        });

        jLabel1.setText("Premio");

        jLabel2.setText("Año");

        txtAño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAñoMouseClicked(evt);
            }
        });
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnRegistrar)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPremiosCaballo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPremiosCaballo);

        jLabel4.setText("Información del caballo");

        textoCodigo.setText("code");

        jLabel3.setText("Código:");

        jLabel5.setText("Nombre:");

        textoNombre.setText("jLabel6");

        jLabel6.setText("Género: ");

        textoGenero.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoCodigo)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNombre)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoGenero))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoCodigo)
                    .addComponent(jLabel5)
                    .addComponent(textoNombre)
                    .addComponent(jLabel6)
                    .addComponent(textoGenero))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAdelante.setText("Adelante");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(147, 147, 147)
                        .addComponent(btnAtras)
                        .addGap(35, 35, 35)
                        .addComponent(btnAdelante)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnAtras)
                    .addComponent(btnAdelante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtPremio.getText().isEmpty() || txtAño.getText().isEmpty()) {
                throw new CompletarCampoVacioException();
            }
            String premio = txtPremio.getText();
            String año = txtAño.getText();
            PremioCaballo premioCaballo = new PremioCaballo(premio, año);
            animal.agregarPremioAlCaballo(premioCaballo);
            AccionRealizadaAnimal accion = new AccionRealizadaAnimal(animal, AccionRealizadaAnimal.REGISTRAR);
            vistaLogIn.getControladorPila().pushAccionPilaUnoAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaPremiosUno(premioCaballo);
            agregarPremioTabla(premioCaballo);
            JOptionPane.showMessageDialog(null, "Se registró el premio del caballo.");
            limpiarCampos();
            vistaLogIn.getControladorPesebrera().escribirPesebreras();
        } catch (CompletarCampoVacioException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VistaListaAnimales vista = new VistaListaAnimales(vistaLogIn, fila, columna);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtPremioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPremioMouseClicked
        // TODO add your handling code here:
        txtPremio.setText(null);
    }//GEN-LAST:event_txtPremioMouseClicked

    private void txtAñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAñoMouseClicked
        // TODO add your handling code here:
        txtAño.setText(null);
    }//GEN-LAST:event_txtAñoMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        if (vistaLogIn.getControladorPila().pilaUnoAnimalesIsEmpty() == false) {
            AccionRealizadaAnimal accion = vistaLogIn.getControladorPila().popAccionPilaUnoAnimales();
            PremioCaballo premioCaballo = null;
            if (accion.getAccion().equals(AccionRealizadaAnimal.REGISTRAR)) {
                Caballo animal = (Caballo) accion.getAnimal();
                premioCaballo = vistaLogIn.getControladorPila().popPilaPremiosUno();
                animal.eliminarPremio(premioCaballo);
                accion.setAccion(AccionRealizadaAnimal.ELIMINAR);
                eliminarObjetosTabla();
                cargarTabla();
            }
            vistaLogIn.getControladorPila().pushAccionPilaDosAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaPremiosDos(premioCaballo);
        } else {
            JOptionPane.showMessageDialog(null, "No se puede retroceder mas.");
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        if (vistaLogIn.getControladorPila().pilaDosAnimalesIsEmpty() == false) {
            AccionRealizadaAnimal accion = vistaLogIn.getControladorPila().popAccionPilaDosAnimales();
            PremioCaballo premioCaballo = null;
            if (accion.getAccion().equals(AccionRealizadaAnimal.ELIMINAR)) {
                Caballo caballo = (Caballo) accion.getAnimal();
                premioCaballo = vistaLogIn.getControladorPila().popPilaPremiosDos();
                caballo.agregarPremioAlCaballo(premioCaballo);
                vistaLogIn.getControladorPesebrera().escribirPesebreras();
                accion.setAccion(AccionRealizadaAnimal.REGISTRAR);
                eliminarObjetosTabla();
                cargarTabla();
            }
            vistaLogIn.getControladorPila().pushAccionPilaUnoAnimales(accion);
            vistaLogIn.getControladorPila().pushPilaPremiosUno(premioCaballo);
        } else {
            JOptionPane.showMessageDialog(null, "No se puede adelantar mas.");
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void txtPremioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPremioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPremioKeyTyped

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtAñoKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable tblPremiosCaballo;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoGenero;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtPremio;
    // End of variables declaration//GEN-END:variables
}
