/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorColaVeterinario;
import controladores.ControladorLote;
import controladores.ControladorPesebrera;
import controladores.ControladorPila;
import controladores.ControladorPocilga;
import controladores.ControladorUsuario;
import controladores.HistorialEliminado;
import controladores.HistorialVenta;
import excepciones.CompletarCampoVacioException;
import excepciones.ContraseñaNoCoincideException;
import excepciones.UsuarioNoRegistradoException;
import javax.swing.JOptionPane;
import modeloAnimales.Animal;
import modeloPersonas.Administrador;
import modeloPersonas.CriadorCerdo;
import modeloPersonas.EncargadoCaballo;
import modeloPersonas.EncargadoGanado;
import modeloPersonas.Usuario;
import modeloPersonas.Veterinario;
import util.Cola;

/**
 *
 * @author SANTIAGO
 */
public class VistaLogIn extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogIn
     */
    private ControladorUsuario controladorUsuario;
    private ControladorPocilga controladorPocilga;
    private ControladorPesebrera controladorPesebrera;
    private ControladorLote controladorLote;
    private HistorialEliminado historialEliminado;
    private ControladorColaVeterinario controladorColaVeterinario;
    private HistorialVenta historialVenta;
    private ControladorPila controladorPila;

    public VistaLogIn() {
        initComponents();
        setLocationRelativeTo(this);
        controladorUsuario = new ControladorUsuario();
        controladorPocilga = new ControladorPocilga();
        controladorPesebrera = new ControladorPesebrera();
        controladorLote = new ControladorLote();
        historialEliminado = new HistorialEliminado();
        controladorColaVeterinario = new ControladorColaVeterinario();
        historialVenta = new HistorialVenta();
        controladorPila = new ControladorPila();
//        Administrador admin = new Administrador("Admin", "123", "Santiago", "Bernal", "123", 20);
//        controladorUsuario.registrarUsuario(admin);
//        Veterinario vete = new Veterinario("Vete", "123", "Andres", "Ocampo", "321", 30);
//        controladorUsuario.registrarUsuario(vete);
//        CriadorCerdo cerdo = new CriadorCerdo("Cerdo", "123", "Criador", "Cerdos", "1234", 50);
//        controladorUsuario.registrarUsuario(cerdo);
//        EncargadoCaballo caballo = new EncargadoCaballo("Caba", "123", "sdf", "gfd", "765432", 1);
//        controladorUsuario.registrarUsuario(caballo);
//        EncargadoGanado ganado = new EncargadoGanado("Gana", "123", "gfdsa", "hgfds", "987654", 2);
//        controladorUsuario.registrarUsuario(ganado);
    }

    private void limpiarCampos() {
        txtUsuario.setText("Usuario");
        txtContraseña.setText("Contraseña");
    }

    public ControladorUsuario getControladorUsuario() {
        return controladorUsuario;
    }

    public ControladorPocilga getControladorPocilga() {
        return controladorPocilga;
    }

    public ControladorPesebrera getControladorPesebrera() {
        return controladorPesebrera;
    }

    public ControladorLote getControladorLote() {
        return controladorLote;
    }

    public HistorialEliminado getHistorialEliminado() {
        return historialEliminado;
    }

    public ControladorColaVeterinario getControladorColaVeterinario() {
        return controladorColaVeterinario;
    }

    public HistorialVenta getHistorialVenta() {
        return historialVenta;
    }

    public ControladorPila getControladorPila() {
        return controladorPila;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LogIn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setText("Usuario");
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");

        btnLogIn.setText("Ingresar");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.setText("Contraseña");
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtContraseña)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnLogIn)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnLogIn)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 290));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/login.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        try {
            if (txtUsuario.getText().isEmpty() || txtContraseña.getText().isEmpty()
                    || txtContraseña.getText().equals("Contraseña")
                    || txtUsuario.getText().equals("Usuario")) {
                throw new CompletarCampoVacioException();
            }
            Usuario usuario = controladorUsuario.buscarUsuario(txtUsuario.getText());
            if (usuario == null) {
                throw new UsuarioNoRegistradoException();
            }
            if (usuario.getContraseña().equals(txtContraseña.getText())) {
                controladorUsuario.setUsuarioLogueado(usuario);
                limpiarCampos();
                if (usuario instanceof Administrador) {
                    VistaAdministrador vista = new VistaAdministrador(this);
                    vista.setVisible(true);
                    this.dispose();
                } else if (usuario instanceof CriadorCerdo) {
                    VistaCriadorDeCerdo vista = new VistaCriadorDeCerdo(this);
                    vista.setVisible(true);
                    this.dispose();
                } else if (usuario instanceof Veterinario) {
                    VistaVeterinario vista = new VistaVeterinario(this);
                    vista.setVisible(true);
                    this.dispose();
                } else if (usuario instanceof EncargadoCaballo) {
                    VistaEncargadoDelCaballo vista = new VistaEncargadoDelCaballo(this);
                    vista.setVisible(true);
                    this.dispose();
                } else {
                    VistaEncargadoDelGanado vista = new VistaEncargadoDelGanado(this);
                    vista.setVisible(true);
                    this.dispose();
                }
            } else {
                throw new ContraseñaNoCoincideException();
            }
        } catch (CompletarCampoVacioException | UsuarioNoRegistradoException
                | ContraseñaNoCoincideException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnLogInActionPerformed

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        // TODO add your handling code here:
        txtContraseña.setText(null);
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        txtUsuario.setText(null);
    }//GEN-LAST:event_txtUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
