/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorUsuario;
import controladores.HistorialVenta;
import javax.swing.table.DefaultTableModel;
import modeloAnimales.Cerdo;
import modeloAnimales.Ganado;
import modeloAnimales.Venta;
import modeloPersonas.CriadorCerdo;
import modeloPersonas.EncargadoCaballo;
import modeloPersonas.EncargadoGanado;
import modeloPersonas.Usuario;

/**
 *
 * @author SANTIAGO
 */
public class VistaHistorialVendidos extends javax.swing.JFrame {

    /**
     * Creates new form VistaHistorialVendidos
     */
    VistaLogIn vistaLogIn;
    ControladorUsuario controladorUsuario;
    DefaultTableModel modeloVentas;
    HistorialVenta historialVenta;

    public VistaHistorialVendidos(VistaLogIn vistaLogIn) {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaLogIn = vistaLogIn;
        controladorUsuario = vistaLogIn.getControladorUsuario();
        historialVenta = vistaLogIn.getHistorialVenta();
        declararColumnasTabla();
        cargarTabla();
        validarAnimal();
    }

    private void declararColumnasTabla() {
        modeloVentas = new DefaultTableModel();
        modeloVentas.addColumn("N.Comprador");
        modeloVentas.addColumn("A.Comprador");
        modeloVentas.addColumn("Telefono");
        modeloVentas.addColumn("Cod.Animal");
        modeloVentas.addColumn("Precio");
        this.tblVentas.setModel(modeloVentas);
    }

    private void cargarTabla() {
        Usuario usuario = controladorUsuario.getUsuarioLogueado();
        if (usuario instanceof CriadorCerdo || VistaAdministrador.rolEscogido.equals("Cerdo")) {
            cargarTablaCerdoVendido();
        } else if (usuario instanceof EncargadoGanado || VistaAdministrador.rolEscogido.equals("Ganado")) {
            cargarTablaGanadoVendido();
        }
    }

    private void cargarTablaGanadoVendido() {
        System.out.println(historialVenta.obtenerTamañoLista());
        for (int i = 0; i < historialVenta.obtenerTamañoLista(); i++) {
            Venta venta = historialVenta.recorrerLista(i);
            if (venta.getAnimalVendido() instanceof Ganado) {
                String[] datos = new String[5];
                datos[0] = venta.getDatosComprador().getNombre();
                datos[1] = venta.getDatosComprador().getApellido();
                datos[2] = venta.getDatosComprador().getTelefono();
                datos[3] = venta.getAnimalVendido().getCodigoString();
                datos[4] = "$" + String.valueOf(venta.getPrecioAnimal());
                modeloVentas.addRow(datos);
            }
        }
    }

    private void cargarTablaCerdoVendido() {
        for (int i = 0; i < historialVenta.obtenerTamañoLista(); i++) {
            Venta venta = historialVenta.recorrerLista(i);
            if (venta.getAnimalVendido() instanceof Cerdo) {
                String[] datos = new String[5];
                datos[0] = venta.getDatosComprador().getNombre();
                datos[1] = venta.getDatosComprador().getApellido();
                datos[2] = venta.getDatosComprador().getTelefono();
                datos[3] = venta.getAnimalVendido().getCodigoString();
                datos[4] = "$" + String.valueOf(venta.getPrecioAnimal());
                modeloVentas.addRow(datos);
            }
        }
    }

    private void validarAnimal() {
        Usuario usuario = controladorUsuario.getUsuarioLogueado();
        if (usuario instanceof CriadorCerdo || VistaAdministrador.rolEscogido.equals("Cerdo")) {
            textoAnimales.setText("Cerdos");
        } else if (usuario instanceof EncargadoGanado || VistaAdministrador.rolEscogido.equals("Ganado")) {
            textoAnimales.setText("Toros");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoAnimales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animales vendidos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        textoAnimales.setText("jLabel1");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(textoAnimales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoAnimales)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Usuario usuario = controladorUsuario.getUsuarioLogueado();
        if (usuario instanceof CriadorCerdo || VistaAdministrador.rolEscogido.equals("Cerdo")) {
            VistaCriadorDeCerdo vista = new VistaCriadorDeCerdo(vistaLogIn);
            vista.setVisible(true);
        } else if (usuario instanceof EncargadoCaballo || VistaAdministrador.rolEscogido.equals("Caballo")) {
            VistaEncargadoDelCaballo vista = new VistaEncargadoDelCaballo(vistaLogIn);
            vista.setVisible(true);
        } else if (usuario instanceof EncargadoGanado || VistaAdministrador.rolEscogido.equals("Ganado")) {
            VistaEncargadoDelGanado vista = new VistaEncargadoDelGanado(vistaLogIn);
            vista.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentas;
    private javax.swing.JLabel textoAnimales;
    // End of variables declaration//GEN-END:variables
}
