/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorPocilga;
import controladores.ControladorUsuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modeloPersonas.Administrador;
import modeloPersonas.Usuario;
import modelosTerrenos.Pocilga;

/**
 *
 * @author SANTIAGO
 */
public class VistaCriadorDeCerdo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form VistaCriadorDeCerdo
     */
    VistaLogIn vistaLogIn;
    JButton[][] botones;
    ControladorPocilga controladorPocilga;
    ControladorUsuario controladorUsuario;

    public VistaCriadorDeCerdo(VistaLogIn vistaLogIn) {
        initComponents();
        setLocationRelativeTo(this);
        controladorPocilga = vistaLogIn.getControladorPocilga();
        controladorUsuario = vistaLogIn.getControladorUsuario();
        this.vistaLogIn = vistaLogIn;
        botones = new JButton[controladorPocilga.retornarFilas()][controladorPocilga.retornarColumnas()];
        cargarBotones();
        btnVolver.setVisible(false);
        validarUsuarioLogeado();
    }

    private void validarUsuarioLogeado() {
        Usuario usuarioLogeado = controladorUsuario.getUsuarioLogueado();
        if (usuarioLogeado instanceof Administrador) {
            btnVolver.setVisible(true);
        }
    }

    private void cargarBotones() {
        int ancho = 60;
        int alto = 60;
        int separado = 60;
        int texto = 1;
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                Pocilga pocilga = controladorPocilga.obtenerPocilga(i, j);
                if (pocilga.getEstado().equals(Pocilga.OCUPADO)) {
                    botones[i][j].setBackground(java.awt.Color.GREEN);
                }
                if (texto == 5 || texto == 13) {
                    botones[i][j].setBounds(
                            ((j + 1) * ancho + separado),
                            (i * alto + separado),
                            ancho, alto);
                } else if (texto > 5 && texto < 9 || texto > 13) {
                    botones[i][j].setBounds(
                            ((j + 1) * ancho + separado),
                            (i * alto + separado),
                            ancho, alto);
                } else {
                    botones[i][j].setBounds(
                            (j * ancho + separado),
                            (i * alto + separado),
                            ancho, alto);
                }
                botones[i][j].setText(String.valueOf(texto));
                botones[i][j].addActionListener(this);
                panelBotones.add(botones[i][j]);
                texto++;
            }
        }
        panelBotones.repaint();
    }

    public void actualizarBotones() {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                Pocilga pocilga = controladorPocilga.obtenerPocilga(i, j);
                if (pocilga.getEstado().equals(Pocilga.OCUPADO)) {
                    botones[i][j].setBackground(java.awt.Color.GREEN);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnEliminados = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotones.setBackground(new java.awt.Color(0, 0, 0, 150));
        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criador de cerdos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnEliminados.setText("Eliminados");
        btnEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminadosActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addGap(127, 127, 127)
                .addComponent(btnEliminados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btnVentas)
                .addGap(71, 71, 71)
                .addComponent(btnCerrarSesion))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addGap(0, 214, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion)
                    .addComponent(btnVentas)
                    .addComponent(btnEliminados)
                    .addComponent(btnVolver)))
        );

        getContentPane().add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 660, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/Cerdos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VistaAdministrador vista = new VistaAdministrador(vistaLogIn);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminadosActionPerformed
        // TODO add your handling code here:
        VistaHistorialEliminados vista = new VistaHistorialEliminados(vistaLogIn);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminadosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        VistaHistorialVendidos vista = new VistaHistorialVendidos(vistaLogIn);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminados;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBotones;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                if (ae.getSource().equals(botones[i][j])) {
                    Pocilga pocilga = controladorPocilga.obtenerPocilga(i, j);
                    if (pocilga.getEstado().equals(Pocilga.DISPONIBLE)) {
                        VistaSeleccionGenero vista = new VistaSeleccionGenero(vistaLogIn, i, j);
                        vista.setVisible(true);
                    } else {
                        VistaListaAnimales vista = new VistaListaAnimales(vistaLogIn, i, j);
                        vista.setVisible(true);
                    }
                    this.dispose();
                }
            }
        }
    }
}
