/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorUsuario;
import excepciones.CompletarCampoVacioException;
import excepciones.UsuarioNoRegistradoException;
import javax.swing.JOptionPane;
import modeloPersonas.Administrador;
import modeloPersonas.EncargadoCaballo;
import modeloPersonas.EncargadoGanado;
import modeloPersonas.Usuario;
import modeloPersonas.Veterinario;

/**
 *
 * @author SANTIAGO
 */
public class VistaGestionInfoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaGestionInfoUsuario
     */
    VistaLogIn vistaLogIn;
    ControladorUsuario controladorUsuario;

    public VistaGestionInfoUsuario(VistaLogIn vistaLogIn) {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaLogIn = vistaLogIn;
        controladorUsuario = vistaLogIn.getControladorUsuario();
        bloquearCamposYBotones();
    }

    private void limpiarCampos() {
        txtId.setText("Identificación");
        txtNombre.setText("Nombre(s)");
        txtApellido.setText("Apellido(s)");
        txtEdad.setText("Edad");
    }

    private void bloquearCamposYBotones() {
        bloquearBotones();
        bloquearCampos();
    }

    private void desbloquearCamposYBotones() {
        desbloquearBotones();
        desbloquearCampos();
    }

    private void desbloquearCampos() {
        txtNombre.setEditable(true);
        txtApellido.setEditable(true);
        txtEdad.setEditable(true);
        textoOtro.setVisible(true);
        txtOtro.setVisible(true);
        txtUsuarioEncontrado.setVisible(true);
        txtId.setEnabled(false);
    }

    private void bloquearCampos() {
        txtNombre.setEditable(false);
        txtApellido.setEditable(false);
        txtEdad.setEditable(false);
        textoOtro.setVisible(false);
        txtOtro.setVisible(false);
        txtOtro.setEditable(false);
        txtUsuarioEncontrado.setVisible(false);
        txtUsuarioEncontrado.setEditable(false);
        txtId.setEnabled(true);
    }

    private void desbloquearBotones() {
        btnEliminar.setEnabled(true);
        btnEditar.setEnabled(true);
    }

    private void bloquearBotones() {
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(false);
    }

    private void llenarCampos(Usuario usuario) {
        if (usuario instanceof Administrador) {
            txtUsuarioEncontrado.setText("Administrador");
            textoOtro.setText("Usuarios registrados");
            txtOtro.setText(String.valueOf(((Administrador) usuario).getNumeroUsuariosRegistrados()));
            desbloquearCampos();
            btnEditar.setEnabled(true);
        } else if (usuario instanceof EncargadoCaballo) {
            txtUsuarioEncontrado.setText("Encargado de caballos");
            desbloquearCamposYBotones();
        } else if (usuario instanceof EncargadoGanado) {
            txtUsuarioEncontrado.setText("Encargado del ganado");
            textoOtro.setText("Toros vendidos");
            txtOtro.setText(String.valueOf(((EncargadoGanado) usuario).getNumeroTorosVendidos()));
            desbloquearCamposYBotones();
        } else if (usuario instanceof Veterinario) {
            txtUsuarioEncontrado.setText("Veterinario");
            textoOtro.setText("Animales atentidos");
            txtOtro.setText(String.valueOf(((Veterinario) usuario).getNumeroAnimalesAtendidos()));
            desbloquearCamposYBotones();
        } else {
            txtUsuarioEncontrado.setText("Criador de cerdos");
            textoOtro.setText("Cerdos vendidos");
            desbloquearCamposYBotones();
        }
        txtNombre.setText(usuario.getNombre());
        txtApellido.setText(usuario.getApellido());
        txtEdad.setText(String.valueOf(usuario.getEdad()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtOtro = new javax.swing.JTextField();
        textoOtro = new javax.swing.JLabel();
        txtUsuarioEncontrado = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnReinicar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión de información", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setText("Identificación");
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 46, 111, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 49, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 45, -1, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setText("Nombre(s)");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 161, 124, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre(s)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 138, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido(s)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 138, -1, -1));

        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.setText("Apellido(s)");
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 161, 120, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 209, -1, -1));

        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.setText("Edad");
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEdadMouseClicked(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 232, 96, -1));

        txtOtro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 232, 120, -1));

        textoOtro.setForeground(new java.awt.Color(255, 255, 255));
        textoOtro.setText("Otro");
        jPanel1.add(textoOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 209, -1, -1));

        txtUsuarioEncontrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioEncontrado.setText("jTextField1");
        jPanel1.add(txtUsuarioEncontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 98, 142, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 302, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 302, -1, -1));

        btnReinicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnReinicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 350, 370));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 389, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/Personal.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VistaAdministrador vista = new VistaAdministrador(vistaLogIn);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtId.getText().isEmpty()) {
                throw new CompletarCampoVacioException();
            }
            String id = txtId.getText();
            Usuario usuario = controladorUsuario.buscarUsuarioPorId(id);
            if (usuario == null) {
                throw new UsuarioNoRegistradoException();
            }
            llenarCampos(usuario);
        } catch (CompletarCampoVacioException | UsuarioNoRegistradoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty()
                    || txtEdad.getText().isEmpty()) {
                throw new CompletarCampoVacioException();
            }
            String id = txtId.getText();
            String nuevoNombre = txtNombre.getText();
            String nuevoApellido = txtApellido.getText();
            int nuevaEdad = Integer.parseInt(txtEdad.getText());
            controladorUsuario.editarInfoUsuario(id, nuevoNombre, nuevoApellido, nuevaEdad);
            JOptionPane.showMessageDialog(null, "Se editó la información");
            limpiarCampos();
            bloquearCamposYBotones();
        } catch (CompletarCampoVacioException | UsuarioNoRegistradoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
        // TODO add your handling code here:
        txtId.setText(null);
    }//GEN-LAST:event_txtIdMouseClicked

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        txtNombre.setText(null);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        // TODO add your handling code here:
        txtApellido.setText(null);
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void txtEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMouseClicked
        // TODO add your handling code here:
        txtEdad.setText(null);
    }//GEN-LAST:event_txtEdadMouseClicked

    private void btnReinicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicarActionPerformed
        // TODO add your handling code here:
        bloquearCamposYBotones();
        limpiarCampos();
    }//GEN-LAST:event_btnReinicarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtId.getText().isEmpty()) {
                throw new CompletarCampoVacioException();
            }
            controladorUsuario.eliminarUsuario(txtId.getText());
            JOptionPane.showMessageDialog(null, "Se eliminó el usuario");
            limpiarCampos();
            bloquearCamposYBotones();
        } catch (CompletarCampoVacioException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnReinicar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoOtro;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOtro;
    private javax.swing.JTextField txtUsuarioEncontrado;
    // End of variables declaration//GEN-END:variables
}
